return {}
-- TODO: this config is causing error update and fix it
-- return {
-- 	'nvim-tree/nvim-tree.lua',
-- 	dependencies = {
-- 		'nvim-tree/nvim-web-devicons',
-- 	},
-- 	config = function()
-- 		-- disable netrw at the very start of your init.lua
-- 		-- vim.g.loaded_netrw = 1
-- 		-- vim.g.loaded_netrwPlugin = 1
--
-- 		-- set termguicolors to enable highlight groups
-- 		vim.opt.termguicolors = true
--
-- 		-- OR setup with some options
-- 		require("nvim-tree").setup({
-- 			on_attach = function(bufnr)
-- 				local api = require ("nvim-tree.api")
--
-- 				local function opts(desc)
-- 				    return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
-- 				end
--
-- 				-- default mappings
-- 				api.config.mappings.default_on_attach(bufnr)
--
-- 				-- custom mappings
-- 				vim.keymap.set('n', '<C-t>', api.tree.change_root_to_parent, { desc='Up', silent = true,nowait = true, noremap = true })
-- 				vim.keymap.set('n', '?',     api.tree.toggle_help, { desc='Help', silent = true,nowait = true, noremap = true })
-- 				vim.keymap.set('n', '<C-e>',function() api.tree.toggle({find_file = false, update_root = false, focus = true,}) end, { desc='Toggle NvimTree', silent = true,nowait = true, noremap = true })
-- 			end,
-- 			sort = {
-- 				sorter = "case_sensitive",
-- 			},
-- 			view = {
-- 				width = 30,
-- 			},
-- 			renderer = {
-- 				group_empty = true,
-- 			},
-- 			filters = {
-- 				dotfiles = true,
-- 			},
-- 		})
-- 	end,
-- }
