return {}
-- TODO: check this out for refactoring code
-- return {
--     "ThePrimeagen/refactoring.nvim",
--     dependencies = {
--         "nvim-lua/plenary.nvim",
--         "nvim-treesitter/nvim-treesitter",
--     },
--     config = function()
--         require("refactoring").setup()
--         vim.keymap.set('v', '<leader>ri',function() require('refactoring').refactor('Inline Variable') end, { noremap = true, silent = true, expr = false })
--
--     end,
-- }
